### ISSUE TITLE
A better way to translate mods is possible

### ISSUE THREAD

**Issue by mquinson** [minetest-mods/intllib#1]
Hello,

your code is nice, but I fear that if adopted, it will be very difficult to use and maintain on the long run. Creating the translation file is not trivial, as there is no equivalent of the xgettext tool. Also, what should be done when an english text is modified? Detecting which translation should be updated and how to modify it sounds very difficult to me.

I think that using the gettext tools such as xgettext and msgupdate is a much better idea. This could be a very good starting point:
http://lua-users.org/lists/lua-l/2010-04/msg00005.html

Thanks for your work,
Mt

**Comment by BrunoMine** [comment]
I believe that if a text was changed in English, it will no longer translated by intllib (this seems perfectly correct).

**Comment by kaeza** [comment]
Please see #11.

**Comment by kaeza** [comment]
Should be fixed by https://github.com/minetest-mods/intllib/commit/b2551f6a2209b8a11b42834cb0d63f5c03a2b95f.
