### ISSUE TITLE
I can not find the localefile.md

### ISSUE THREAD

**Issue by BrunoMine** [minetest-mods/intllib#13]
This file would need to exist in the [doc](https://github.com/minetest-mods/intllib/tree/master/doc) directory ???

**Comment by kaeza** [comment]
Oh, looks like I forgot to add it in the previous README split.

Fixed by https://github.com/minetest-mods/intllib/commit/b98f01b2da0e6815724d02bf0de1abf2f6a8a086.

Thank you for reporting!
