### ISSUE TITLE
How should we number the variables?

### ISSUE THREAD

**Issue by BrunoMine** [minetest-mods/intllib#14]
I'm translating some strings, and I came across the following situation:
Mod homedecor
![problem](https://cloud.githubusercontent.com/assets/7986261/22371377/0423a5f6-e47e-11e6-95a8-f951b2a88de2.jpg)
What is the correct way to concatenate the variables in the translated string?

**Comment by kaeza** [comment]
It depends on the context of the translation.

From the example you give:

* `@1` is the player name (the one moving things).
* `@2` is the location name (for example, a locked cabinet).
* `@3` is the name of the owner.
* `@4` is a position.

You will probably need something like `@1 tentou acessar @2 pertenecente a @3 em @4` which will be formatted as `kaeza tentou acessar homedecor:locked_whatever pertenecente a BrunoMine em (123,456,789)`.

**Comment by BrunoMine** [comment]
Is it possible to define in what sequence the variables are placed?
For examplo:
`@2 @4 que pertence a @3 recebeu tentativa de acesso de @1` 
`homedecor:locked_whatever (123,456,789) que pertence a BrunoMine recebeu tentativa de acesso de kaeza` 
Or is it necessary to use `%s`?

**Comment by kaeza** [comment]
You can reorder the fields and translate in whatever way makes the most sense.

Use of `%s` is discouraged as it does not allow reordering, but you should use whatever the source text uses.

**Comment by BrunoMine** [comment]
Sorry to reopen the issue, but I want to take the opportunity to ask one more thing.

The old interface allowed to commen each string. 
This helps the translator a lot to understand the context of some sentences.

Is there this feature in the new interface?

I would also like to know if it is possible to describe more than one reviewer in the same translation file.

**Comment by kaeza** [comment]
>The old interface allowed to commen each string. [...] Is there this feature in the new interface?

I believe `xgettext` (the tool used to generate the catalogs) can extract comments from the source code and put them in the relevant entries, so yes.

I will have to go through the sources and add comments, so it will take some time. In the mean time, if you have some doubts feel free to ask. Most strings should be quite self-explanatory. In strings like `Bed (@1)` , the parameter usually means a color or material (e.g. `Bed (blue)` or `Nightstand with One Drawer (oak)`). For things like `@1 (Locked)` it's usually the name of an item (e.g. `Oven (Locked)`). Etc, etc.

>I would also like to know if it is possible to describe more than one reviewer in the same translation file.

You mean the `Last-Translator` field? Past translators are visible in the git history of the project or they can be listed in a separate file depending on the project. Just put your name in there for now (email is optional).

**Comment by BrunoMine** [comment]
Item names are really easy to translate, just search for them in creative mode. The problem is the console messages or formspecs that appear in specific moments to the player.

For now I'm listing the names of translators in the translation file header comment.

**Comment by BrunoMine** [comment]
You can create notes for each message. It's perfect.
