### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by zaoqi** [minetest-mods/intllib#15]
https://travis-ci.org/minetest/minetest_game/builds/200241990
Checking mods/intllib/gettext.lua                 6 warnings

    mods/intllib/gettext.lua:4:7: unused variable 'floor'

    mods/intllib/gettext.lua:106:8: unreachable code

    mods/intllib/gettext.lua:113:7: unused variable 'domains'

    mods/intllib/gettext.lua:114:7: unused variable 'dgettext_cache'

    mods/intllib/gettext.lua:115:7: unused variable 'dngettext_cache'

    mods/intllib/gettext.lua:169:33: shadowing upvalue argument 'str' on line 167

Checking mods/intllib/init.lua                    1 warning

    mods/intllib/init.lua:110:17: shadowing upvalue 'gettext' on line 74
Checking mods/intllib/lib.lua                     1 warning

    mods/intllib/lib.lua:50:14: unused variable 'err'
Checking mods/intllib/tools/findtext.lua          1 warning

    mods/intllib/tools/findtext.lua:126:5: shadowing definition of variable 'i' on line 15
Checking mods/intllib/tools/updatetext.lua        10 warnings

    mods/intllib/tools/updatetext.lua:10:10: mutating read-only global variable 'string'

    mods/intllib/tools/updatetext.lua:58:3: unused global variable 'old_msg_mode'

    mods/intllib/tools/updatetext.lua:60:3: unused global variable 'old_msg_mode'

    mods/intllib/tools/updatetext.lua:84:16: unused function 'printf'

    mods/intllib/tools/updatetext.lua:93:4: accessing undefined variable 'output'

    mods/intllib/tools/updatetext.lua:94:8: shadowing definition of variable 'e' on line 79

    mods/intllib/tools/updatetext.lua:95:23: accessing undefined variable 'output'

    mods/intllib/tools/updatetext.lua:101:16: unused function 'printf'

    mods/intllib/tools/updatetext.lua:101:16: variable 'printf' was previously defined on line 84

    mods/intllib/tools/updatetext.lua:126:16: shadowing definition of variable 'e' on line 79

**Comment by kaeza** [comment]
Fixed by https://github.com/minetest-mods/intllib/commit/122d1a83cc380eb3919e28d20531b001c5cf8bac.

Thank you for reporting!

**Comment by kaeza** [comment]
See also: c667cd0de67e01792072f66ee9f0d539f18f75ad
