### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/intllib#28]
Hi,

to package this mod for Debian, I would need tagged releases, as taking random commits is generally not a good idea.

Some simple scheme like using dates is enough, and commands like "git tag 20180708 && git push --tags" should do the trick.

Thanks

**Comment by SnarkBoojum** [comment]
Is the project abandoned?

**Comment by kaeza** [comment]
I created a new release 20180811. Is that correct?

https://github.com/minetest-mods/intllib/releases/tag/20180811

**Comment by SnarkBoojum** [comment]
Yes, perfect! Thanks!
