### ISSUE TITLE
Some MT 5 translation efforts

### ISSUE THREAD

**Issue by Zweihorn** [minetest-mods/intllib#29]
@kaeza 👍  Thanks for your excellent work and sustainable efforts.

IMHO the LUA-code mod **Intllib** is a very helpful and quite realiable tool. I very much appreciate the compliance with the _GNU gettext_ toolchain.

On basis of your **intllib 20180811 release** I am currently establishing a tweaked code and new  **game_intllib** with a central **locale** and _template.pot_ as an umbrella for most if not all of the mods in the _minetest_game-5.0.1_ mods tree. This is WIP and the first drafts and results are promising.

Please have a look at my proposals at:

- [Translating minetest_game #1932](https://github.com/minetest/minetest_game/issues/1932#issuecomment-491230384)
- [game_intllib - Re: [Mod] Internationalization Library [intllib]](https://forum.minetest.net/viewtopic.php?f=11&t=4929&p=346616#p346616)

I would seek to synchronise my little project with your excellent work piece if this would be convenient to you.

**Comment by Zweihorn** [comment]
In a parallel effort and as a minor addition I established an effort to make 'intllib' compatible to the new MT game translation and the new MT 5 `minetest.get_translator` function. This should allow a more seemless using of external mods which make use of 'intllib.lua' until and beyond the new MT game translation scheme is truly in place hopefully.

Please consider: [MT game translation - 'intllib' is dead? Long live 'intllib' ...](https://github.com/minetest-mods/intllib/pull/30)

Thank you for your consideration and certainly your good efforts in the past.
[snoopy (Zweihorn)] 2019-05-15

**Comment by Zweihorn** [comment]
I renamed the topic of this issue #29 to honor `intllib` and the community MT 5 translation efforts.

**Comment by Wuzzy2** [comment]
Minetest Game has been translated already, this issue is now outdated.

**Comment by Zweihorn** [comment]
Old new:
AFAIK they came in the night and grabbed my translation commits like thieves in the night. Could be called teamwork but my mileage may vary, I presume. 🥲 

Have fun with MT.

🌻
