### ISSUE TITLE
Set up a wiki for this project

### ISSUE THREAD

**Issue by BrunoMine** [minetest-mods/intllib#5]
I'm really willing to work in this amazing project.
I wish there were a wiki in several languages teaching use it.
I have a developer friend, he wants to internationalize mods but not understood how it works.
I do not think it's a good idea to put it in the README.txt then the wiki GitHub can a good idea.
I desire to collaborate in the project.

**Comment by BrunoMine** [comment]
Another option would be the creation of PDF documents to guide the use of intllib.

**Comment by kaeza** [comment]
There's a [page](http://wiki.minetest.net/Mods/IRC) for the mod in the main Minetest wiki. Feel free to create the Mods/IRC/Pt page there (or submit a `README-pt.txt` or so).

Maybe it should be linked to somewhere in the README. Leaving this open so I don't forget later.

**Comment by BrunoMine** [comment]
You are referring to the IRC mod.
I'm really going to start to translate the wiki to Portuguese. (I already ordered my account and I'm waiting)

About intlib:
You want me to translate the README.txt?
I would like to be a contributor, but if you want not this, I can send you the file by email.

**Comment by kaeza** [comment]
> You are referring to the IRC mod.

Sorry, wrong link. Should not respond while half asleep.

> You want me to translate the README.txt?
> I would like to be a contributor, but if you want not this, I can send you the file by email.

If you know how to send a Pull Request, please do so. Sending the translated file via e-mail is fine too. I'll take care of merging it, with proper credit, of course.

**Comment by kaeza** [comment]
I'm not sure if a wiki page is needed.

**Comment by sofar** [comment]
Closing this for now. The minetest.net wiki seems like the right location for this at this time.
